services:
  - type: web
    name: websocket-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://websocket-client-eight.vercel.app
    healthCheckPath: /health
